### ISSUE TITLE
No docs folder

### ISSUE THREAD

**Issue by timsamoff** [APUGames/Lawbringer#1]
I don't see your docs folder with the beginnings of the Concept Doc. Please get this pushed asap.

**Comment by timsamoff** [comment]
@ChrisDuran117: Please push your project with a docs folder/Concept Doc asap!

**Comment by timsamoff** [comment]
This is not resolved on GitHub yet, so only close it when it's complete.

**Comment by ChrisDuran117** [comment]
On GitHub, it says I have a concept doc folder and my concept doc is in
there. Is it not there for you?

**Comment by timsamoff** [comment]
Look here:

> [https://github.com/APUGames/Lawbringer](https://github.com/APUGames/Lawbringer)

No docs folder.

Do you mean in GitKraken? If so, you may just not have pushed yet?

**Comment by ChrisDuran117** [comment]
I found the issue. The docs folder is in the Project 2 folder itself, but
not in the main master branch.

**Comment by timsamoff** [comment]
Ok. Move stuff around and re-push. ;)

**Comment by ChrisDuran117** [comment]
Will do!
